// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsGjMoVJGECWhMjAg5g-MmweZ3zQlR424',
    appId: '1:787337297332:web:a0aa2eba2e6c2e587ec6e1',
    messagingSenderId: '787337297332',
    projectId: 'gokulfirebaseapplicaation',
    authDomain: 'gokulfirebaseapplicaation.firebaseapp.com',
    storageBucket: 'gokulfirebaseapplicaation.firebasestorage.app',
    measurementId: 'G-N9KD58E07X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgAyxKksX5jc48fysH-byONOeub2mc8tk',
    appId: '1:787337297332:android:cdd01aca64f682287ec6e1',
    messagingSenderId: '787337297332',
    projectId: 'gokulfirebaseapplicaation',
    storageBucket: 'gokulfirebaseapplicaation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDriwzIQcwCjY7UPF4uc50seBTemTkpfA',
    appId: '1:787337297332:ios:ea20a0b070d7b2307ec6e1',
    messagingSenderId: '787337297332',
    projectId: 'gokulfirebaseapplicaation',
    storageBucket: 'gokulfirebaseapplicaation.firebasestorage.app',
    iosBundleId: 'com.example.gokulFirebaseApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDriwzIQcwCjY7UPF4uc50seBTemTkpfA',
    appId: '1:787337297332:ios:ea20a0b070d7b2307ec6e1',
    messagingSenderId: '787337297332',
    projectId: 'gokulfirebaseapplicaation',
    storageBucket: 'gokulfirebaseapplicaation.firebasestorage.app',
    iosBundleId: 'com.example.gokulFirebaseApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsGjMoVJGECWhMjAg5g-MmweZ3zQlR424',
    appId: '1:787337297332:web:6b97cab03efa3b387ec6e1',
    messagingSenderId: '787337297332',
    projectId: 'gokulfirebaseapplicaation',
    authDomain: 'gokulfirebaseapplicaation.firebaseapp.com',
    storageBucket: 'gokulfirebaseapplicaation.firebasestorage.app',
    measurementId: 'G-8Q5SBWFKK5',
  );
}
